version: '3'
services:
  dev:
    image: node:16-alpine
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: npm run dev
    ports:
      - 3000:3000
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=niners
      - POSTGRES_PASSWORD=niners
    logging:
          options:
            max-size: 10m
            max-file: "3"
    ports:
      - '5438:5432'